name = "nakai"
version = "0.11.0"
licences = ["MIT"]
description = "HTML generation for Gleam, on the server or anywhere else"
repository = { type = "github", user = "nakaixo", repo = "nakai" }
links = [
  { title = "Website", href = "https://nakaixo.github.io" },
  { title = "Sponsor", href = "https://github.com/sponsors/aslilac" },
]

internal_modules = ["nakai/internal/*"]
gleam = ">= 1.0.0"

[dependencies]
gleam_stdlib = ">= 0.36.0 and < 2.0.0"

[dev-dependencies]
envoy = "~> 1.0"
gleam_json = "~> 0.7"
gleeunit = "~> 1.0"
glychee = "~> 0.3"
simplifile = "~> 1.0"
