name = "nakai"
version = "0.4.2"
licences = ["MIT"]
description = "A server-side rendering framework for building web apps with Gleam ✨"
repository = { type = "github", user = "nakaixo", repo = "nakai" }

[dependencies]
gleam_stdlib = "~> 0.28"

[dev-dependencies]
gleam_erlang = "~> 0.18"
gleam_json = "~> 0.5"
gleeunit = "~> 0.10"

[documentation]
hidden_modules = ["nakai/codegen/*", "nakai/render", "nakai/render/*"]
